# Example benchmark configuration

# Benchmark config
benchmark_name: bert_2
sampling_rate: 1.0 # 100% of the data
num_trials: 5 # Number of trials to run for each model
data_path: data_v2

# Chatbots to benchmark with their common names
chatbots:
  - "*""

# Model settings
#model:
#  class: CNNClassifier
#  params:
#    kernel_width: 3
model:
  class: BERTTimeSeriesClassifier
  params:
    fc_dims: [128, 64]
    dropout_rate: 0.3
    model_name: 'distilbert-base-uncased'

training:
  # Training parameters
  batch_size: 32
  max_epochs: 50
  learning_rate: 0.00005
  patience: 10
  test_size: 20
  valid_size: 5
  seed: 42
