# Example benchmark configuration

# Benchmark config
benchmark_name: lgmb_time_mitigations
sampling_rate: 1
num_trials: 5 # Number of trials to run for each model
data_path: data/main
feature_modes:
#  - "Both"
#  - "Data Size Only"      # Test how mitigations affect different features
  - "Time Only"

# Chatbots to benchmark with their common names. >=0.8 AUPRC from time data.
chatbots:
  - azuregpt41nano
  - gpt41nano
#  - azuredeepseekr1
#  - claudehaiku
#  - azuregpt41nano
#  - geminiflash
#  - azuregpt4o
#  - amazonnovalitev1
#  - azuregpt41nano
#  - azuregpt41mini
#  - azuregpt4o
#  - claudehaiku
#  - azuregpt4omini
#  - geminiflash
#  - azuregpto1mini
#  - gpt4omini
#  - geminiflashlight


# --- Mitigation Sets ---
# Define different combinations of mitigations to test
mitigations:
  none: [] # Baseline - no mitigation

  remove_empty_time_entries:
    - type: RemoveZeroTimeEntries
      params: {}
  
  injection_adaptive_50pct_1:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 1.0, adaptive_min_samples: 5}
  
  injection_adaptive_50pct_0.5:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 0.5, adaptive_min_samples: 5}
  
  injection_adaptive_75pct_0.5:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.75, median_time_multiplier: 0.5, adaptive_min_samples: 5}
  
  injection_adaptive_25pct_0.5:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.25, median_time_multiplier: 0.5, adaptive_min_samples: 5}
  
  injection_adaptive_100pct_0.5:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.5, adaptive_min_samples: 5}

  injection_adaptive_50pct_0.75:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 0.75, adaptive_min_samples: 5}
  
  injection_adaptive_75pct_0.75:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.75, median_time_multiplier: 0.75, adaptive_min_samples: 5}
  
  injection_adaptive_25pct_0.75:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 0.25, median_time_multiplier: 0.75, adaptive_min_samples: 5}
  
  injection_adaptive_100pct_0.75:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.75, adaptive_min_samples: 5}

  injection_adaptive_100pct_1:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 1.0, adaptive_min_samples: 5}
  
  injection_adaptive_100pct_0.25:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.25, adaptive_min_samples: 5}
  
  injection_adaptive_100pct_0.125:
    - type: AdaptivePacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.125, adaptive_min_samples: 5}

  injection_50pct_1:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 1.0}
  
  injection_50pct_0.5:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 0.5}
  
  injection_75pct_0.5:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.75, median_time_multiplier: 0.5}
  
  injection_25pct_0.5:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.25, median_time_multiplier: 0.5}
  
  injection_100pct_0.5:
    - type: PacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.5}

  injection_50pct_0.75:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.50, median_time_multiplier: 0.75}
  
  injection_75pct_0.75:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.75, median_time_multiplier: 0.75}
  
  injection_25pct_0.75:
    - type: PacketInjectionMitigation
      params: {injection_probability: 0.25, median_time_multiplier: 0.75}
  
  injection_100pct_0.75:
    - type: PacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.75}

  injection_100pct_1:
    - type: PacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 1.0}
  
  injection_100pct_0.25:
    - type: PacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.25}
  
  injection_100pct_0.125:
    - type: PacketInjectionMitigation
      params: {injection_probability: 1.0, median_time_multiplier: 0.125}
    
  batching_1:
    - type: PacketBatchingMitigation
      params: {batch_size: 1}

  batching_2:
    - type: PacketBatchingMitigation
      params: {batch_size: 2}
  
  batching_3:
    - type: PacketBatchingMitigation
      params: {batch_size: 3}
  
  batching_4:
    - type: PacketBatchingMitigation
      params: {batch_size: 4}
  
  batching_5:
    - type: PacketBatchingMitigation
      params: {batch_size: 5}

  batching_6:
    - type: PacketBatchingMitigation
      params: {batch_size: 6}

  batching_7:
    - type: PacketBatchingMitigation
      params: {batch_size: 7}

  batching_8:
    - type: PacketBatchingMitigation
      params: {batch_size: 8}

  batching_9:
    - type: PacketBatchingMitigation
      params: {batch_size: 9}
  
  batching_10:
    - type: PacketBatchingMitigation
      params: {batch_size: 10}

  batching_11:
    - type: PacketBatchingMitigation
      params: {batch_size: 11}

  batching_12:
    - type: PacketBatchingMitigation
      params: {batch_size: 12}

  batching_13:
    - type: PacketBatchingMitigation
      params: {batch_size: 13}

  batching_14:
    - type: PacketBatchingMitigation
      params: {batch_size: 14}

  batching_15:
    - type: PacketBatchingMitigation
      params: {batch_size: 15}

  batching_16:
    - type: PacketBatchingMitigation
      params: {batch_size: 16}

  batching_17:
    - type: PacketBatchingMitigation
      params: {batch_size: 17}

  batching_18:
    - type: PacketBatchingMitigation
      params: {batch_size: 18}

  batching_19:
    - type: PacketBatchingMitigation
      params: {batch_size: 19}

  batching_20:
    - type: PacketBatchingMitigation
      params: {batch_size: 20}

# Model settings
model:
  class: LightGBMClassifier
  params:
    n_estimators: 5000
    learning_rate: 0.02

# Model settings
#model:
#  class: AttentionBiLSTMClassifier
#  params:
#    hidden_size: 128
#    num_layers: 2
#    dropout_rate: 0.3
#    embedding_dim: 32
#    fc_dims: [128, 64]
#    bidirectional: true
#    attention_dim: 64

training:
  # Training parameters
  batch_size: 32
  max_epochs: 100
  learning_rate: 0.0002
  patience: 20
  test_size: 20
  valid_size: 5
  seed: 42
